### PR TITLE
adding README to JUnit example

### PR DESCRIPTION
**Pull request by YosiBergman**

### CODE REVIEW

**Comment by gad-ron** [comment]
Please continue with the fullexample

**Comment by YosiBergman** [comment]
Adding the rest of the JUnit file including :

1. Framework to connect to automation REST server
2. Example how to user & expose different REST services
3. Example how to wait for jobs to end, check status, confirm, etc

**Comment by gad-ron** [comment]
1 README 
	[Missing A what is it section]	
	Ci/CD test automation example
	How to verify control-m workflows runs using JUnit
	
	
	
	[Generation of the rest client instructions]
		https://<ENDPOINT>:8443/automation-api/yaml
		
		the parameters we used in the cli
		
		mvn install
			The artifact generated 

	
2. pom.xml

	clean the parent project
	
	Change the name of the artifact to
		testAutomationJunitExample

		
3 tests
	remove the ConnectionTest.java
	
	
	tests/resources
	readme.txt -> README.MD
	
	remove
		myCertification.cer

4. Main
	RunServices
	
	Main comment what is this class
		the 1 -2 hilghts of this class and methods

**Comment by YosiBergman** [comment]
adding changes following your comments

**Pull request merged**
